version: '3.8'

services:
  # --- База данных ---
  db:
    image: postgres:15-alpine
    container_name: bonafide_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - bonafide_network

  # --- Backend (Django) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bonafide_backend
    # Запускаем Gunicorn на 8000 порту
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application --workers 3
    volumes:
      - staticfiles_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bonafide_network

  # --- Frontend (Next.js) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Важно: используем prod версию
    container_name: bonafide_frontend
    env_file:
      - .env
    expose:
      - 3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bonafide_network

  # --- Nginx (Прокси) ---
  nginx:
    image: nginx:alpine
    container_name: bonafide_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Статика Django (CSS админки)
      - staticfiles_volume:/app/staticfiles:ro
      # Медиа (Картинки товаров)
      - media_volume:/app/media:ro
      # Сертификаты (Твои пути на сервере -> Пути внутри контейнера)
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - bonafide_network

  # --- Certbot (Для автообновления SSL, если понадобится) ---
  certbot:
    image: certbot/certbot
    volumes:
      - /var/www/certbot:/var/www/certbot

volumes:
  postgres_data:
  staticfiles_volume:
  media_volume:

networks:
  bonafide_network:
    driver: bridge